services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    command: npm run build

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: npm run dev

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SSL_CERTIFICATE_PATH=${SSL_CERTIFICATE_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./client/dist:/var/www/html
      - ${SSL_CERTIFICATE_ORIGIN_PATH}:${SSL_CERTIFICATE_PATH}:ro
      - ${SSL_KEY_ORIGIN_PATH}:${SSL_KEY_PATH}:ro
    command: /bin/bash -c "envsubst '$$SERVER_PORT $$SSL_CERTIFICATE_PATH $$SSL_KEY_PATH' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - server
