services:
  client:
    image: jjadedbay/portfolio:client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  server:
    image: jjadedbay/portfolio:server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"