services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

